server:
  port: 0

spring:
  application:
    name: picpay
  datasource:
    url: jdbc:postgresql://localhost:5433/accounts
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
#  datasource:
#    url: jdbc:h2:mem:devdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true            # Habilita o console web do H2
#      path: /h2-console         # Caminho para o console web
  jpa:
    hibernate:
      ddl-auto: update # Controle de criação e atualização de esquema (veja as observações abaixo)
    show-sql: true # Exibir as consultas SQL no console
    properties:
      hibernate:
        format_sql: true # Formatar a exibição de SQL
#        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${spring.application.instanceId:${random.value}}

message:
  error:
    cpf: "CPF inválido."
    email: "EMAIL inválido."
    notAccount: "Conta nao localizado na base de dados. "
    account: "Conta nao pode ser nulo"
    agency: "Agencia nao pode ser nulo"
    balance: "Saldo nao pode ser nulo."
